### ISSUE TITLE
export openssl MD4 APIs

### ISSUE THREAD

**Issue by rameshrv** [spacemonkeygo/openssl#100]
This openssl go package has been of great use to us so far in our project !!

However, in our product, we need openssl APIs for MD4 hash (unfortunately we use MSCHAPv2). 
I have added required changes in my forked repo, and I am temporarily referencing that forked repo in our code-base. I would like to switch to the original repo (this one) instead of using a forked repo for all openssl calls.

I wish to know if it was okay to create a PR for opening up openssl MD4 APIs ? I realize MD4 is not widely used, but some projects (like us) are still using MD4. (I could also add MD5 hash along with it.) Please let me know.

**Comment by zeebo** [comment]
Sure, I'd be willing to accept that.

**Comment by rameshrv** [comment]
Thank you! will put up a PR soon !

**Comment by rameshrv** [comment]
was stuck with other tasks, finally I got to the PR !

**Comment by zeebo** [comment]
Closed by #104.
