### ISSUE TITLE
Support for ED25519 keys/cert

### ISSUE THREAD

**Issue by parasssh** [spacemonkeygo/openssl#102]
The Ed25519 support has been added to openssl in the version 1.1.1. This version is not yet released by OpenSSL but they do have pre-release versions. I'd like to check if a enhancement PR that adds support for Ed Certificates/keys with the generate/sign/verify operations is of interest.

I could also add it for Ed448.

**Comment by zeebo** [comment]
Sure. Ed25519 is my favorite.

**Comment by zeebo** [comment]
Closed by #103.
