### ISSUE TITLE
Getting SSL_ERROR_WANT_READ and running out of memory.

### ISSUE THREAD

**Issue by saurabhsuniljain** [spacemonkeygo/openssl#131]
I am using this library in one of my server and when there is a huge load I get SSL_ERROR_WANT_READ error and then in handling this error `fillInputBuffer` function is called which is consuming a lot of memory by allocating a buffer and then I am running out of memory and server is crashing.

[Error Handling code](https://github.com/spacemonkeygo/openssl/blob/85c7f475b6f75ff4afea3bb003f8b5ca711f8945/conn.go#L228)

1) In what scenario we get SSL_ERROR_WANT_READ error?  What can I do to avoid this?
2) Is there any parameter I can pass to avoid handling of this error? What may be the effects of this?

**Comment by zeebo** [comment]
SSL_ERROR_WANT_READ is returned by openssl when it is stating that it needs data. That's why the library is allocating a buffer to read into and pass to openssl.

I think your server is just needs more resources or you need to handle less work.
