### ISSUE TITLE
getting fatal error: 'openssl/bio.h' file not found on m1 mac

### ISSUE THREAD

**Issue by nurjamil** [spacemonkeygo/openssl#148]
In file included from ../../pkg/mod/github.com/spacemonkeygo/openssl@v0.0.0-20181017203307-c2dcc5cca94a/bio.go:17:
./shim.h:21:10: fatal error: 'openssl/bio.h' file not found
#include <openssl/bio.h>
         ^~~~~~~~~~~~~~~
1 error generated.

Ive already install pkgconfig 
export LDFLAGS="-L/opt/homebrew/opt/openssl/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl/include"
export PATH="/opt/homebrew/opt/openssl/bin:$PATH"
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl/lib/pkgconfig"

pkg-config --variable=includedir openssl

**Comment by nurjamil** [comment]
solved:

export CGO_LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
export CGO_CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"

**Comment by johansetia** [comment]
> solved:
> 
> export CGO_LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib" export CGO_CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"

sorry. i got this errors and how to fix it
```BASH
ld: warning: ignoring file /opt/homebrew/opt/openssl@1.1/lib/libssl.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/opt/openssl@1.1/lib/libcrypto.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```
