### ISSUE TITLE
VerifyPKCS1v15 fails indeterministicly

### ISSUE THREAD

**Issue by JoeBruner** [spacemonkeygo/openssl#30]
This is probably related to issue #19 

I have the following method:

    func (s myConf) Verify(data []byte, sig []byte) (bool, error) {
    	digest, err := openssl.SHA256(data)
	    if err != nil {
		    return false, err
    	}

	    if err := (*(s.public)).VerifyPKCS1v15(openssl.SHA256_Method, digest[:], signature); err != nil {
		    return false, err
    	} else {
	    	return true, nil
    	}
    }

I just recently noticed that my unit tests _usually_ pass, though occasionally they will fail with the error:

    verifypkcs1v15: failed to finalize verify

Maybe every 3rd or 4th time I run it is fails.  If I click run again, it will pass.

**Comment by jtolds** [comment]
Oh, did you figure it out @JoeBruner ? what was the issue?

**Comment by JoeBruner** [comment]
Well, I discovered that I had a different issue.  My code was generating a signature for a structure that contained a `map[string]bool`.  I was doing a:

    for k, _ := range m {
       buf.WriteString(k)
    }

but that is wrong, as the ordering of keys returned is (intentionally) randomized by Go.  I need to first sort the keys before adding to the buffer.  Until I fix that problem, I'm closing the issue.  If I still have problems, I'll re-open the issue.
