### ISSUE TITLE
Lack of examples on how to generate certificates

### ISSUE THREAD

**Issue by norx85** [spacemonkeygo/openssl#33]
The documentation lack of examples on how to generate certificates.
I tried to generate a signed p12 but i was unable to do that.
I also started a [stackoverflow post](http://stackoverflow.com/questions/30308881/how-to-generate-signed-p12-with-openssl-lib-in-go) on it but no one has replied, so probably no one know how to do that, some examples are definitely necessary.

**Comment by lunixbochs** [comment]
There's code here in the cert test here: https://github.com/spacemonkeygo/openssl/blob/master/cert_test.go

There's also code in my poxd project that generates certs and keys: https://github.com/lunixbochs/poxd/blob/master/tls.go#L13

Only the MarshalPEM function is implement however, not PKCS12.

**Comment by zeebo** [comment]
Question seems answered. Closing.
