### ISSUE TITLE
want more ciphers to be supported!

### ISSUE THREAD

**Issue by buglomi** [spacemonkeygo/openssl#46]
I found this package only support fewer ciphers as below:
openssl.SetCiphers("ALL")

Testing AES256-GCM-SHA384...YES
Testing AES256-SHA256...YES
Testing AES256-SHA...YES
Testing CAMELLIA256-SHA...YES
Testing AES128-GCM-SHA256...YES
Testing AES128-SHA256...YES
Testing AES128-SHA...YES
Testing CAMELLIA128-SHA...YES
Testing DES-CBC3-SHA...YES

the morden configuration about ssl_ciphers list as below:

ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-S128-GCM-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-A:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4

So what should I do ?

**Comment by buglomi** [comment]
when I load dhparam and set ec ,that is work! 
thanks!

**Comment by zeebo** [comment]
Seems like you solved your problem, so I'm closing. Please reopen if not.

**Comment by gaillard** [comment]
Note to the next guy, a call to SSL_CTX_set_ecdh_auto (wrapped since its a macro), will do all the curve setting etc.
