### ISSUE TITLE
GCM ciphers not built on OS X even when installed OpenSSL supports them

### ISSUE THREAD

**Issue by spaghetti2514** [spacemonkeygo/openssl#48]
Making this bug report on request of https://github.com/rfjakob/gocryptfs/issues/15#issuecomment-169510632

OS X no longer ships openssl as of OS X 10.11, and as such an installed version of openssl is probably new enough to support GCM, but they are not built in this project so long as the platform is darwin ala
https://github.com/spacemonkeygo/openssl/blob/master/ciphers_gcm.go#L15
with no checks made to see if the installed openssl provides support or not.

Personally I have OpenSSL 1.0.2e installed on OS X 10.11.2 and removing the "!darwin" from that linked file allows these bindings to continue to build just fine

**Comment by zeebo** [comment]
I'm going to look at the linked pull request in this issue and see if it fixes it. Closing this in favor of the pull request tracking.
