### ISSUE TITLE
Go 1.6 support

### ISSUE THREAD

**Issue by jtolds** [spacemonkeygo/openssl#51]
We know, we know.

Just filing this ticket so people can track our progress on fixing this.

**Comment by vrecan** [comment]
Is there a known issue? I have it running on 1.6 right now.

**Comment by azdagron** [comment]
There is currently unsafe cgo usage. I believe this can be detected setting GODEBUG=cgocheck=2 (the default is 1). We have a fix implemented, we are just musing at this point if it has the right tradeoffs.

**Comment by zeebo** [comment]
Fixed by fb0c387e74932c5ac3da434bfee75e32e7961601
