### ISSUE TITLE
http get request authentication

### ISSUE THREAD

**Issue by evandromartines** [spacemonkeygo/openssl#53]
must make an Authenticating on a SOAP server for client: http.Client = { } using digital .pfx certificate type , it is possible using spacemonkeygo / openssl .
Have any example?

Thanks

**Comment by zeebo** [comment]
Sorry, I don't know anything about a .pfx file or what it contains, but if you can set up an ssl context you should be able to make TLS handshakes with it. Maybe look at examples using the openssl C api and map that to our wrapper?
