### ISSUE TITLE
SSL handshake fails on el capitan

### ISSUE THREAD

**Issue by ansel1** [spacemonkeygo/openssl#57]
I opened pull request #56 to fix the build on OSX by using the "brew" build tag, but the tests don't pass.

The TestOpenSSLSimple and other tests which exercise SSL handshaking fail on OSX. Not sure why. SSH_get_error returns SSL_ERROR_SSL, but ERR_get_error returns 0. I don't see any other indication why the ssl handshake is failing.

I'm using el capitan and golang 1.6.2.  Tests pass normally on debian.

**Comment by zeebo** [comment]
Are you still having this issue on a recent version of the library? Closing because they pass for me locally on openssl 1.1 and openssl 1.0.
