### ISSUE TITLE
variable 'writeBioMethod' has initializer but incomplete type

### ISSUE THREAD

**Issue by cophey** [spacemonkeygo/openssl#68]
> ./bio.go:40:1: error: variable 'writeBioMethod' has initializer but incomplete type
 static BIO_METHOD writeBioMethod = {
 ^
./bio.go:54:1: error: variable 'readBioMethod' has initializer but incomplete type
 static BIO_METHOD readBioMethod = {
 ^

![n0syw4llt z w ceh2sfof](https://cloud.githubusercontent.com/assets/7555270/22639674/26c04eac-ec8a-11e6-968c-e276b0c2a8c7.png)

What is the problem?Thanks!

**Comment by zenixls2** [comment]
what is your openssl version? do you set the correct include path for lib openssl?

**Comment by cophey** [comment]
Set LD_LIBRARY_PATH,and then it is ok.Thanks.

**Comment by Trophime** [comment]
@cophey could you be more specific, please?
I run into the same issue when trying to rebuild the zesty ubuntu package on Debian/Testing. 
What shall I put into LD_LIBRARY_PATH (the path to libssl.so)?
Thanks

**Comment by premranderia** [comment]
@Trophime facing the same issue ? Did you resolve it ?
