### ISSUE TITLE
TLS Session ticket  

### ISSUE THREAD

**Issue by brk0v** [spacemonkeygo/openssl#7]
I tried to implement ssl tls ticket feature. But haven't enough skill.  
So can someone help me with it. Any examples will be good. I stack with callback function implementation in cgo.
I'm talking about this: https://www.openssl.org/docs/ssl/SSL_CTX_set_tlsext_ticket_key_cb.html

Thank you.

**Comment by zeebo** [comment]
I think I did this without knowing this was a thing. Sorry! Gonna close for now.
